- project:
    check:
      jobs:
        - build-sphinx-docs
    gate:
      jobs:
        - build-sphinx-docs
    post:
      jobs:
        - publish-zuul-docs
        - publish-openstack-sphinx-docs-infra
