- project:
    check:
      jobs:
        - zuul-tox-docs
    gate:
      jobs:
        - zuul-tox-docs
    promote:
      jobs:
        - zuul-promote-docs
    release:
      jobs:
        - zuul-publish-tox-docs
        - opendev-release-python
